version: "3.7"

services:
  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: mass-gameap_server_1
      APP_PORT: 8000

  server:
    image: gameap/gameap
    restart: always
    volumes:
        - ${APP_DATA_DIR}/data/gameap-storage:/var/www/gameap/storage
    environment:
        ADMIN_PASSWORD: fpwPOuZD
        APP_LANG: en
        DB_CONNECTION: mysql
        DB_HOST: db
        DB_DATABASE: gameap
        DB_USERNAME: gameap
        DB_PASSWORD: gameap
    ports:
      - "8000:8000"
    depends_on:
          - db
  db:
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: rootpass
        MYSQL_DATABASE: gameap
        MYSQL_USER: gameap
        MYSQL_PASSWORD: gameap
