version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mass-gameap_server_1
      APP_PORT: 8000

  server:
    image: gameap/gameap
    restart: always
    volumes:
      - ./data/gameap-storage:/var/www/gameap/storage
    environment:
      ADMIN_PASSWORD: fpwPOuZD
      APP_LANG: en
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_DATABASE: gameap
      DB_USERNAME: gameap
      DB_PASSWORD: gameap
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: gameap
      MYSQL_USER: gameap
      MYSQL_PASSWORD: gameap
    volumes:
      - ./data/db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
