version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: mass-mikopbx_server_1
      APP_PORT: 2165

  server:
    image: ghcr.io/mikopbx/mikopbx-x86-64
    entrypoint: /sbin/docker-entrypoint
    init: true
    tty: true
    volumes:
      - ${APP_DATA_DIR}/data/cf:/cf
      - ${APP_DATA_DIR}/data/storage:/storage
    environment:
      - PUID=1000
      - PGID=1000
      - ID_WWW_USER=1000
      - ID_WWW_GROUP=1000
      - PBX_NAME=MikoPBXFirst
      - PBX_FIREWALL_ENABLED=0
      - PBX_FAIL2BAN_ENABLED=0
      - SSH_PORT=123
      - WEB_PORT=2165
      - WEB_HTTPS_PORT=8443
      - SIP_PORT=5060
      - TLS_PORT=5061
      - RTP_PORT_FROM=10000
      - RTP_PORT_TO=10800
      - IAX_PORT=4569
      - AMI_PORT=5038
      - AJAM_PORT=8088
      - AJAM_PORT_TLS=8089
      - BEANSTALK_PORT=4229
      - REDIS_PORT=6379
      - GNATS_PORT=4223
