version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: mass-mikopbx_server_1
      APP_PORT: 2165

  server:
    image: ghcr.io/mikopbx/mikopbx-x86-64
    entrypoint: /sbin/docker-entrypoint
    init: true
    tty: true
    ports:
      - "5060:5060/tcp"
      - "5060:5060/udp"
      - "8443:8443"
      - "10000-10800:10000-10800"
      - "4569:4569"
      - "5038:5038"
      - "8088:8088"
      - "4229:4229"
      - "6379:6379"
      - "4223:4223"
    volumes:
      - ${APP_DATA_DIR}/data/cf:/cf
      - ${APP_DATA_DIR}/data/storage:/storage
    environment:
      - PUID=1000
      - PGID=1000
      - ID_WWW_USER=1000
      - ID_WWW_GROUP=1000
      - PBX_NAME=Umbrel MikoPBX
      - PBX_FIREWALL_ENABLED=0
      - PBX_FAIL2BAN_ENABLED=0
      - SSH_PORT=123
      - WEB_PORT=2165
      - WEB_HTTPS_PORT=8443
      - SIP_PORT=5060
      - RTP_PORT_FROM=10000
      - RTP_PORT_TO=10800
      - IAX_PORT=4569
      - AMI_PORT=5038
      - AJAM_PORT=8088
      - BEANSTALK_PORT=4229
      - REDIS_PORT=6379
      - GNATS_PORT=4223
